### ISSUE TITLE
Chat Open 24/7

### ISSUE THREAD

**Issue by MarcusPlayz517** [Manliketjb/chat#1]
chat stays open like this all the time, any way to close it, or is there a fix? 

![notepad++_qbCtX6aY8Y](https://user-images.githubusercontent.com/100505762/157045710-501266b2-986a-43e0-9e9f-207076d822bc.png)

**Comment by Manliketjb** [comment]
not a bug, that's just how it is made. probably going to add a hide keybind and a clear chat command

**Comment by MarcusPlayz517** [comment]
awesome

**Comment by Alivemonstor** [comment]
https://github.com/Manliketjb/chat/pull/3

clear chat
