### ISSUE TITLE
hide chat?

### ISSUE THREAD

**Issue by KRW28** [Manliketjb/chat#2]
Is there a way to hide the chat?

**Comment by Alivemonstor** [comment]
https://github.com/Manliketjb/chat/pull/3

Fixes this

**Comment by LividDS** [comment]
Is there a button to press to toggle it between hidden/active/show like in some other chat scripts?

**Comment by Manliketjb** [comment]
> Is there a button to press to toggle it between hidden/active/show like in some other chat scripts?

no, you can only clear the chat, other than that it does hide after a little time
